### ISSUE TITLE
"Unknown variable: value_to_collect"

### ISSUE THREAD

**Issue by djvill** [santiagobarreda/FastTrack#13]
When running Track folder with "Aggregate" selected, I get the error "Unknown variable: value_to_collect". It appears to be related to a new option in the pause window for the aggregate tool for which a default isn't set in the Track folder script.

**Comment by santiagobarreda** [comment]
Ok I think its because I didnt test the aggregate function when it runs automatically in a folder analysis, I only tested it when run independently, sorry. I just uploaded a fix that I think should resolve the issue, I just declare the variable before the pause form now.

**Comment by djvill** [comment]
Great, it works for me now.
