### ISSUE TITLE
When tracking folder, info window holds up computer

### ISSUE THREAD

**Issue by djvill** [santiagobarreda/FastTrack#14]
When doing Track Folder, the repeated `writeInfoLine` calls cause the Info window to be brought into focus at least once per second, effectively freezing out the user from doing anything else in the background while Fast Track is running. For large folders, this means making the computer unavailable for long amounts of time. It'd be nice to turn off this behavior.

**Comment by santiagobarreda** [comment]
This doesn't happen on my computer so its good to know about. The info window freezes for me whenever I touch Praat so it is of limited utility anyways. I accep[ted the pull request and so am closing the issue.
