### ISSUE TITLE
Edit folder: empty formula

### ISSUE THREAD

**Issue by rsquizz** [santiagobarreda/FastTrack#18]
When trying to use the Edit folder tool, following the [documentation](https://github.com/santiagobarreda/FastTrack/wiki/Edit-folder), Praat will create a list of strings of .Formant files in the correct formants_edited folder, load in the first .Formant and corresponding .wav, create a Spectrogram object, then throw the error below.

Looking at the script, it seems that the .number_of_coefficients_for_formant_prediction parameter isn't being passed to the findError procedure.

<img width="255" alt="Screen Shot 2022-01-19 at 5 10 03 PM" src="https://user-images.githubusercontent.com/26158861/150244111-55f47ba0-a231-486a-9b33-80541b626b2e.png">

Praat 6.1.51
MacOS 11.6 (Big Sur)

**Comment by santiagobarreda** [comment]
Thanks for letting me know, I'll fix this very soon.

**Comment by rsquizz** [comment]
> 

Thank you! Do you have an estimated timeframe for this?

**Comment by santiagobarreda** [comment]
Sorry for the delay, its fixed now. Let me know if there are any remaining problems or if anything else comes up.
