### ISSUE TITLE
Path problems

### ISSUE THREAD

**Issue by MargauxDubuis** [santiagobarreda/FastTrack#2]
Dear all,

We (with @agricolamz) discovered a problem with paths on Windows. The notion of upper level with two dots seems not to work on Windows. I currently use Windows 10 and Praat version  6.1.32. 

Recently we tried to extract formants using a Textgrid and an audio (around 10 minutes length) and got the following error message: 
![image](https://user-images.githubusercontent.com/48757553/103242446-7b533d80-4956-11eb-928d-af2c6206caf8.png)

**Comment by santiagobarreda** [comment]
Hi, it definitely works on Windows, I wrote it in Windows. In general, the functions work without issues as of right now. Its hard for me to tell why you got that error. Is it possible that the file is open somewhere or something like that?

**Comment by santiagobarreda** [comment]
Hi, it definitely works on Windows, I wrote it in Windows! Its usually the only operating system that I am confident things work in. In general, the functions work without issues as of right now. Its hard for me to tell why you got that error. Is it possible that the file is open somewhere or something like that?

**Comment by santiagobarreda** [comment]
Were you able to resolve the issue? Can I close this?

**Comment by MargauxDubuis** [comment]
Thank you for your answer!
No we didn't, we will check it this week.

**Comment by agricolamz** [comment]
Dear Santiago, we solved our problems thank you for FastTrack!

**Comment by santiagobarreda** [comment]
I'm glad you found it useful!

**Comment by robertfromont** [comment]
I saw this issue, and upgrading Praat fixed it.
