### ISSUE TITLE
Error when tracking folder

### ISSUE THREAD

**Issue by stefanocoretta** [santiagobarreda/FastTrack#23]
Hi, sorry to bother you with something different. I am trying to track some files and when I use the `Track folder...` I get the error below but it works fine when I use the `Track folder (lite)...`. I am attaching the culprit file if you want to have a look.

- [380221.zip](https://github.com/santiagobarreda/FastTrack/files/14248597/380221.zip)

<img width="520" alt="Screenshot 2024-02-12 at 18 39 31" src="https://github.com/santiagobarreda/FastTrack/assets/6429302/532cb39c-de8f-4134-8b83-8fe903bd128d">

**Comment by santiagobarreda** [comment]
Hi, I just tried the file you sent and it worked with no error. I am using the version currently on GitHub. 

![image](https://github.com/santiagobarreda/FastTrack/assets/20233295/7e488400-8bcd-423a-b19e-d3ac716d1d24)

**Comment by stefanocoretta** [comment]
:( I am also using the latest version from GH. I am on macOS tho. Could it be that?

**Comment by stefanocoretta** [comment]
This is most strange... I added `writeInfoLine: ""` before

`writeFileLine:  folder$ + "/infos/" + .basename$ + "_info.txt", ""`

In `trackFolder.praat` and the error does not come up any more... I have no idea what is causing it tbh nor why adding a `writeInfoLine` statement makes it go away (I tried with other commands and that didn't fix it, only writing/appending to the Info window).

Also, the error comes up specifically with that one file only, not with the other files in the folder 🤷
