### ISSUE TITLE
The winning setting?

### ISSUE THREAD

**Issue by BettyJJ** [santiagobarreda/FastTrack#26]
The plugin can run analyses with different settings and output the winning formant tracks. This works great. But I would like to know the winning setting, too. Is there a way to see that? Thank you very much!

**Comment by santiagobarreda** [comment]
Are you talking about the lite version or the full algorithm? The winning setting is recorded in the winners.csv setting, among other places, in the full algorithm.

**Comment by BettyJJ** [comment]
I followed these steps https://github.com/santiagobarreda/FastTrack/wiki/Installation.
That' the full version, I guess?

The setting I'd like to see is the maximum formant frequency and number of formants that yields the best results. But maybe I misunderstood. I just noticed the readme says it always looks for 5.5 formants. The results sometimes show fewer formants, so I thought this setting was not constant.

**Comment by santiagobarreda** [comment]
You set the number of formants to optimize over, either 3 or 4. It always looks for 5.5 formants. You install one version but decide if you run the full or lite version. I can't tell what you did based on your response. In any case I believe the winning analysis is recorded in the winners.csv file.
