### ISSUE TITLE
Output files documentation

### ISSUE THREAD

**Issue by robertfromont** [santiagobarreda/FastTrack#4]
It would be great if this wiki page were filled in:

https://github.com/santiagobarreda/FastTrack/wiki/Output-files

**Comment by santiagobarreda** [comment]
I am just about to start working on this again after leaving it for a few weeks. I usually work on the things people seem to care about first, so I can definitely fill this in. 

I know I need to explain: 1) a list of all the kind of files generated 2) the naming conventions 3) the structure of the info files, among other things. Is there one of these that you would like to see first?

**Comment by robertfromont** [comment]
All this would be great. I was specifically asked:

> are the lighter colored lines the raw track and the darker the smoothed track? Which one is actually extracted?

I found [the answer to the first question](https://github.com/santiagobarreda/FastTrack/wiki/Plots), but went to this page looking for the second.

**Comment by robertfromont** [comment]
(by 'extracted' they meant 'written to the CSV file')

**Comment by santiagobarreda** [comment]
Ok Ill start working on it. I appreciate you pointing out the missing documentation, I wrote the wiki and then changed the software quite a bit right after and didn't update the wiki even after it stabilized a bit. 

If you have any suggestions about improvements to the existing functionality or additional functions I would appreciate it, my plan is to continuously improve it and I would like it to be useful to people. I also want to clean up the code, which I know is a mess, and comment it to allow for customizability but that will probably be in the next few months.

**Comment by santiagobarreda** [comment]
The user can select which information is extracted:

https://github.com/santiagobarreda/FastTrack/wiki/Options

I updated the pages with information about plots and file outputs. 
https://github.com/santiagobarreda/FastTrack/wiki/Output-files
https://github.com/santiagobarreda/FastTrack/wiki/Plots
