### ISSUE TITLE
Plots documentation images

### ISSUE THREAD

**Issue by robertfromont** [santiagobarreda/FastTrack#5]
FYI the images on this page seem to be broken:

https://github.com/santiagobarreda/FastTrack/wiki/Plots

**Comment by santiagobarreda** [comment]
yeah a lot doesn't work on the wiki, Last fall I kept updating it then the software in a cycle and got sick of it because I was constantly changing it. I think a lot of the wiki is slightly wrong and I will be updating it in the coming days, thank you.

**Comment by santiagobarreda** [comment]
fixed.
