### ISSUE TITLE
"Extract vowels with TextGrid..." pause window too tall

### ISSUE THREAD

**Issue by djvill** [santiagobarreda/FastTrack#9]
The pause window for "Extract vowels with TextGrid..." spills off the vertical space on my screen, and because of the way tabbing works in Praat, there's no way to access the "Ok" button:
![image](https://user-images.githubusercontent.com/22134338/121760305-e0eb4e80-cade-11eb-80ec-66305049a4fe.png).

It would be nice to have a setting that hides the "Click to Read" dropdowns to save vertical space, since that info is in the wiki anyway.

**Comment by santiagobarreda** [comment]
Thanks for noting this. I don't want to add an option for this unless absolutely necessary. I will probably find a way to shrink the book, which is only 800 pixels now.

**Comment by djvill** [comment]
Understandable. Sounds good.

**Comment by santiagobarreda** [comment]
I compressed all the help boxes into one drop down and otherwise saved space. This way users can keep the help on the pause window and still have it fit on their screen. I will make sure that all the pause windows are no taller than the Praat window. Thanks.
